version: "2"
plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-1-30-0
exclude_patterns:
- config/
- db/
- features/
- lib/tasks/cucumber.rake
- script/
- spec/
- vendor/
