version: "3.8"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: rubik
      MYSQL_USER: user
      MYSQL_PASSWORD:
    expose:
      - "3306"
    volumes:
      - mysql:/var/lib/mysql

  redis:
    image: redis
    expose:
      - "6739"
    volumes:
      - redis:/data

  sidekiq:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bundle exec sidekiq
    volumes_from:
      - app
    env_file:
      - .env
    depends_on:
      - db
      - redis

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/var/www/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

volumes:
  mysql:
  redis:
