version: "3.8"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: rubik
      MYSQL_USER: user
      MYSQL_PASSWORD:
    expose:
      - "3306"
    volumes:
      - mysql:/var/lib/mysql

  redis:
    image: redis
    expose:
      - "6739"
    volumes:
      - redis:/data

  sidekiq:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    command: bundle exec sidekiq
    volumes_from:
      - app
    env_file:
      - .env.production
      - .env.production.local
    depends_on:
      - db
      - redis

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/var/www/app
      - assets:/var/www/app/public/assets
    env_file:
      - .env.production
      - .env.production.local
    depends_on:
      - db
      - redis

  web:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes_from:
      - app
    volumes:
      - ./docker/web/nginx.conf:/etc/nginx/conf.d/default.conf
      - /var/run/docker.sock:/tmp/docker.sock:ro

volumes:
  assets:
  mysql:
  redis:
