version: 2.1
orbs:
  ruby: circleci/ruby@1.8.0
  node: circleci/node@5.0.2
jobs:
  build:
    resource_class: large
    parallelism: 4
    docker:
      - image: cimg/ruby:2.7.6-browsers
      - image: cimg/mysql:5.7.36
        environment:
          MYSQL_DATABASE: circle_ruby_test
          MYSQL_ROOT_PASSWORD: passw0rd
    environment:
      RACK_ENV: test
      RAILS_ENV: test
    steps:
      - checkout
      - run: mkdir -p test-results test-results/rspec test-results/cucumber
      - run: gem install bundler -v 1.17.3
      - node/install:
          install-yarn: true
          node-version: '16.15.1'
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
      - run: sudo curl --output /usr/local/bin/phantomjs https://s3.amazonaws.com/circle-downloads/phantomjs-2.1.1; sudo chmod 755 /usr/local/bin/phantomjs
      - run: |-
          mkdir -p config && echo 'test:
            adapter: mysql2
            encoding: utf8
            host: 127.0.0.1
            port: 3306
            username: root
            password: passw0rd
            database: circle_ruby_test
          ' > config/database.yml
      - run:
      # Our primary container isn't MYSQL so run a sleep command until it's ready.
          name: Waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          command: 'bundle exec rails db:schema:load --trace'
      - ruby/rspec-test:
          include: spec/**/*_spec.rb
          out-path: test-results/rspec
      - store_test_results:
          path: test-results/rspec
      - run: |
          FEATURE_FILES=$(circleci tests glob "features/**/*.feature" | circleci tests split --split-by=timings)
          bundle exec cucumber --format junit --out test-results/cucumber -- ${FEATURE_FILES}
      - store_test_results:
          path: test-results/cucumber
      - store_artifacts:
          path: test-results/cucumber
      - run: |
          if [[ "$CIRCLE_NODE_INDEX" == "0" ]]; then
            bundle exec rails ets_pdf:etl
          fi
      - run: |
          RUBOCOP_FILES=$(circleci tests glob "app/**/*.rb" | circleci tests split --split-by=timings)
          bundle exec rubocop --format junit --out test-results/rubocop/results.xml -- ${RUBOCOP_FILES}
      - store_test_results:
          path: test-results/rubocop
      - store_artifacts:
          path: test-results/rubocop
      - run: |
          VIEW_FILES=$(circleci tests glob "app/views/**/*.haml" | circleci tests split --split-by=timings)
          bundle exec haml-lint app/views -- ${VIEW_FILES}
      - run: |
          JS_FILES=$(circleci tests glob "app/assets/javascripts/**/*.js" | circleci tests split --split-by=timings)
          yarn run eslint ${JS_FILES}
