# Action Cable uses Redis by default to administer connections, channels, and sending/receiving messages over the WebSocket.
development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: rubik_production
