default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV['DB_POOL'] || ENV['RAILS_MAX_THREADS'] || 5 %>

local: &local
  <<: *default
  username: root
  password:
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>

development:
  <<: *local
  database: rubik_development

test: &test
  <<: *local
  database: rubik_test

cucumber:
  <<: *test

production:
  <<: *local
  database: rubik
