name: "Update Contributors"

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 1 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Update Contributors
      run: |
        curl --location --request GET "https://api.github.com/repos/${{ github.repository }}/contributors"\
          --header 'Accept: application/vnd.github+json' \
          --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}"\
          | jq '[map({user: .login, profile_url: .html_url, profile_image_url: .avatar_url}) | .[] | select(.user != "depfu[bot]") | select(.user != "dependabot[bot]")]'\
           > config/contributors.json
    - name: Create pull request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: update-contributors
        branch-suffix: timestamp
